### ISSUE TITLE
Erro 302 ao fazer deploy de arquivos

### ISSUE THREAD

**Issue by charliston** [alvimm/vtex-cms-sauce#3]
Estamos com o seguinte erro ao fazer deploy de arquivos:
```
Error: Couldn't save file: /bluefoot/projeto/build/arquivos/1.emp-1-3011b93afe486e3b77b4.js (Error: 302)
    at _callee9$ (/bluefoot/projeto/node_modules/vtex-cms-sauce/lib/index.js:588:21)
    at tryCatch (/bluefoot/projeto/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/bluefoot/projeto/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/bluefoot/projeto/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/bluefoot/projeto/node_modules/vtex-cms-sauce/lib/index.js:31:191)
    at /bluefoot/projeto/node_modules/vtex-cms-sauce/lib/index.js:31:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error while sending files: Error [Error]: 
    at (/bluefoot/projeto/node_modules/@bluefoot/deployr/lib/index.js:258:67)
    at Generator.next (<anonymous>)
    at step (/bluefoot/projeto/node_modules/@bluefoot/deployr/lib/index.js:22:221)
    at _next (/bluefoot/projeto/node_modules/@bluefoot/deployr/lib/index.js:22:409)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

O processo de deploy de templates funciona normalmente. Alguma ideia do motivo dessa resposta 302 do CMS da VTEX?

**Comment by guilhermemarconi** [comment]
@charliston acredito que isso seja alguma alteração feita por parte da VTEX, na ponta deles

**Comment by charliston** [comment]
Eu imaginei que fosse isso mesmo. Tentei debugar pra resolver mas não tive sucesso.

**Comment by alvim** [comment]
Oi, @charliston 

Posso tentar resolver isso dentro dos próximos dias, mas não tenho previsão...
Porém, se vc ou alguém conseguir resolver, por favor, não deixa de fazer uma PR! 😄

**Comment by charliston** [comment]
Obrigado @alvimm !
Se eu encontrar a solução também, mandarei o PR.

**Comment by edceds** [comment]
Alguém encontrou uma solução para essa resposta 302?

**Comment by guilhermemarconi** [comment]
@eduardofidera eu acredito que isso seja algo no servidor da VTEX. Já tentamos algumas alternativas, mas não tivemos sucesso.
